
# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number/{max}
    controller: App\Controller\LuckyController::number

# config/routes.yaml

default:
    path: /
    controller: App\Controller\HomeController::home

# routers_test为路由名称
routers_test:
    # /router为URL路径
    path: /router
    # controller值的格式为：控制器类名::方法名
    controller: App\Controller\RoutefunController::test
